# Cargo configuration for Passkey project
# This file enables custom aliases and build configurations

[alias]
# Enable `cargo xtask` command to run tasks from the xtask package
# Usage: cargo xtask <command> [args...]
# Example: cargo xtask init --env dev
xtask = "run --package xtask --"

[build]
# Default target for cargo lambda builds
# Uncomment when using aarch64 builds consistently
# target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
# Configure cross-compilation for AWS Lambda (Graviton2)
# Requires appropriate toolchain: rustup target add aarch64-unknown-linux-gnu
linker = "aarch64-linux-gnu-gcc"

# Environment-specific configuration
[env]
# Set default AWS region if not specified
# AWS_DEFAULT_REGION = "us-west-2"